package com.mbg.imp;

import com.mbg.entity.CourseEntity;
import com.mbg.entity.CourseEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    int countByExample(CourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    int deleteByExample(CourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    int insert(CourseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    int insertSelective(CourseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    List<CourseEntity> selectByExample(CourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    CourseEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseEntity record, @Param("example") CourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    int updateByExample(@Param("record") CourseEntity record, @Param("example") CourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    int updateByPrimaryKeySelective(CourseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Thu Jan 17 14:29:16 CST 2019
     */
    int updateByPrimaryKey(CourseEntity record);
}